#!/bin/sh
set -eu

mysql -uroot -p"${MYSQL_ROOT_PASSWORD}" <<EOSQL
CREATE DATABASE IF NOT EXISTS project_db;
CREATE DATABASE IF NOT EXISTS task_db;
GRANT ALL PRIVILEGES ON project_db.* TO '${MYSQL_USER}'@'%';
GRANT ALL PRIVILEGES ON task_db.* TO '${MYSQL_USER}'@'%';
FLUSH PRIVILEGES;
EOSQL
